import path from 'path'
import fs from 'fs-extra'
import chalk from 'chalk'
import ora from 'ora'

export async function syncGraphCommand() {
  const spinner = ora('Scanning directory...').start()
  const cwd = process.cwd()
  const targetDir = path.join(cwd, 'src')

  if (!(await fs.pathExists(targetDir))) {
    spinner.warn(chalk.yellow('Directory src/ not found. Skipping graph generation.'))
    return
  }

  const nodes = new Set<string>()
  const edges: { from: string, to: string }[] = []

  async function walk(dir: string) {
    const files = await fs.readdir(dir)
    for (const file of files) {
      const fullPath = path.join(dir, file)
      const stat = await fs.stat(fullPath)
      
      if (stat.isDirectory()) {
        await walk(fullPath)
      } else if (file.endsWith('.ts') || file.endsWith('.js')) {
        const relativePath = path.relative(cwd, fullPath)
        nodes.add(relativePath)
        
        const content = await fs.readFile(fullPath, 'utf-8')
        // Match import ... from '...'
        const importRegex = /import\s+(?:.*?\s+from\s+)?['"](.*?)['"]/g
        let match
        while ((match = importRegex.exec(content)) !== null) {
          let importPath = match[1]
          // If it's a relative import, resolve it
          if (importPath.startsWith('.')) {
            const resolvedPath = path.resolve(path.dirname(fullPath), importPath)
            // It might miss the extension, let's just append .ts if it exists
            let finalRelative = path.relative(cwd, resolvedPath)
            if (!finalRelative.endsWith('.ts') && !finalRelative.endsWith('.js')) {
              // Try appending .ts
              if (await fs.pathExists(path.join(cwd, finalRelative + '.ts'))) {
                finalRelative += '.ts'
              } else if (await fs.pathExists(path.join(cwd, finalRelative, 'index.ts'))) {
                finalRelative = path.join(finalRelative, 'index.ts')
              }
            }
            edges.push({ from: relativePath, to: finalRelative })
            nodes.add(finalRelative) // ensure target node exists
          }
        }
      }
    }
  }

  try {
    await walk(targetDir)
    
    // Build Mermaid
    let mermaid = '# Codebase Architecture Graph\n\n```mermaid\ngraph TD\n'
    
    // Group by directory
    const dirMap = new Map<string, string[]>()
    for (const node of nodes) {
      const dir = path.dirname(node)
      if (!dirMap.has(dir)) dirMap.set(dir, [])
      dirMap.get(dir)!.push(node)
    }

    const safeId = (p: string) => p.replace(/[^a-zA-Z0-9]/g, '_')

    for (const [dir, files] of dirMap.entries()) {
      if (dir === '.') {
        for (const f of files) {
          mermaid += `    ${safeId(f)}["${path.basename(f)}"]\n`
        }
      } else {
        mermaid += `    subgraph ${safeId(dir)}["${dir}"]\n`
        for (const f of files) {
          mermaid += `        ${safeId(f)}["${path.basename(f)}"]\n`
        }
        mermaid += `    end\n`
      }
    }

    mermaid += '\n'
    
    // Add edges
    const uniqueEdges = new Set<string>()
    for (const edge of edges) {
      const e = `    ${safeId(edge.from)} --> ${safeId(edge.to)}`
      if (!uniqueEdges.has(e)) {
        mermaid += e + '\n'
        uniqueEdges.add(e)
      }
    }

    mermaid += '```\n\n> This graph is automatically generated by Bonjay.'

    const docsDir = path.join(cwd, 'docs')
    await fs.ensureDir(docsDir)
    await fs.writeFile(path.join(docsDir, 'architecture.md'), mermaid, 'utf-8')

    spinner.succeed(chalk.green('Architecture graph synced to docs/architecture.md'))
  } catch (error: any) {
    spinner.fail(chalk.red('Failed to sync graph: ' + error.message))
  }
}
