// This file is AUTO-GENERATED by scripts/generate-loader.js
// DO NOT EDIT MANUALLY.

import './ai-persona/index.js'
import './cs-fundamentals/index.js'
import './data-and-systems/index.js'
import './engineering-practices/index.js'
import './project-context/index.js'
import './security/index.js'
import './software-design/index.js'
import './version-control/index.js'
