import type { SkillDef } from '../skills/registry.js'

export const geminiFormatter = (skill: SkillDef): string => {
  const priorityCounts = skill.rules.reduce(
    (acc, rule) => {
      acc[rule.priority] = (acc[rule.priority] ?? 0) + 1
      return acc
    },
    {} as Record<string, number>
  )

  const priorityTable = Object.entries(priorityCounts)
    .map(([p, count]) => `| **${p}** | ${count} |`)
    .join('\n')

  return `---
name: ${skill.id}
description: ${skill.description}
metadata:
  version: "1.1.0"
  group: ${skill.groupId}
  rules_count: ${skill.rules.length}
  engine: gemini-antigravity
---

# ${skill.name}

${skill.longDescription ?? skill.description}

## Rules Overview (Gemini Optimized)

| Priority | Count |
|---|---|
${priorityTable}

## How to Use

${skill.howToUse ?? `Ask your AI assistant to review code for ${skill.name.toLowerCase()} best practices.`}

## Routing Logic

${skill.routingLogic ?? `Use this skill when working with code that involves ${skill.id.replace(/-/g, ' ')}.`}
`
}

export const cursorFormatter = (skill: SkillDef): string => {
  return `---
name: ${skill.id}
description: ${skill.description}
---

# ${skill.name} (Cursor Rule)

> [!IMPORTANT]
> Apply these rules when working in files related to ${skill.id.replace(/-/g, ' ')}.

${skill.description}

## Contextual Guidance
${skill.routingLogic ?? 'Apply automatically based on file patterns.'}

## Instructions
${skill.howToUse ?? 'Follow the specific rules defined in the rules/ directory.'}

---
Generated by Bonjay for Cursor.
`
}

export const defaultFormatter = (skill: SkillDef): string => {
  return `# ${skill.name}\n\n${skill.description}`
}
