import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const skillsDir = path.resolve(__dirname, '../src/skills')
const loaderFile = path.resolve(skillsDir, 'loader.ts')

function generateLoader() {
  console.log('🔍 Scanning skills...')
  
  const entries = fs.readdirSync(skillsDir, { withFileTypes: true })
  const skillDirs = entries
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .filter(name => {
      const indexPath = path.join(skillsDir, name, 'index.ts')
      return fs.existsSync(indexPath)
    })
    .sort()

  const imports = skillDirs.map(dir => `import './${dir}/index.js'`).join('\n')

  const content = `// This file is AUTO-GENERATED by scripts/generate-loader.js
// DO NOT EDIT MANUALLY.

${imports}
`

  fs.writeFileSync(loaderFile, content, 'utf-8')
  console.log(`✅ Generated ${loaderFile} with ${skillDirs.length} skills.`)
}

generateLoader()
